
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer";
import Header from "@/components/header";
import Providers from "@/app/providers";
import ThemeBackground from "@/components/theme-background"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" suppressHydrationWarning >
      <body>
        <Providers>
          
            <Header />
            <ThemeBackground>
            <main className="md:pt-[3.5rem] pt-[7.25rem]">
              {children}
            </main>
            </ThemeBackground>
            <Footer />
          
        </Providers>
      </body>
    </html>
  );
}