import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 서버 컴포넌트에서는 메타데이터를 내보낼 수 있습니다
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 서버 컴포넌트 레이아웃
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body>
      <Header />
      <main>
        {children}
        </main>
        <Footer />
      </body>
      
    </html>
  );
}
